/* eslint-disable */
// THIS FEATURE-FLAGS FILE IS AUTOGENERATED,
// REMOVAL OR CHANGES WILL CAUSE RELATED TYPES TO STOP WORKING
import 'quasar/dist/types/feature-flag';

declare module 'quasar/dist/types/feature-flag' {
  interface QuasarFeatureFlags {
    store: true;
  }
}
